version: '3.7'

volumes:
    mysqldb:

services:
    techblog:
        container_name: techblog_container
        build: .
        image: techblog_image
        restart: always
        #env_file: 
        #    - ./generated/personalblog/.env
        ports:
            - 127.0.0.1:2368:2368
        volumes:
            - ./config.production.json:/var/lib/ghost/config.production.json
        environment:
            #NODE_ENV: 'production'
            #"url": "https://blog.bensoer.com"
#            "admin_url": "http://admin.blog.bensoer.com"
            "database__client": "mysql"
            "database__connection__host": "mysql"
            "database__connection__user": "${MYSQL_USER}"
            "database__connection__password": "${MYSQL_PASSWORD}"
            "database__connection__database": "${MYSQL_DATABASE}"
            "adapters__storage__active": "s3"
            "adapters__storage__region": "us-east-1"
            "GHOST_STORAGE_ADAPTER_S3_PATH_BUCKET": "debenstack-assets"
            "GHOST_STORAGE_ADAPTER_S3_PATH_PREFIX": "techblog/content/images"
            AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
            AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
            AWS_DEFAULT_REGION: "us-east-1"
        depends_on:
            - mysql
    mysql:
        image: mysql:5.7 # 5.7 is currently in prod. ghost 5 wants 8
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
        ports:
            - 3306:3306
        expose:
            - '3306'
        volumes:
            - mysqldb:/var/lib/mysql
            #- ./mysql.local.conf:/etc/alternatives/my.cnf
            #- ./mysql.local.conf:/etc/mysql/mysql.cnf
            #- ./database_init.sql:/docker-entrypoint-initdb.d/database_init.sql
